spring.application.name=springboot-bookmanager
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=Ldp1704110!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver